id: elastic-agent-sw2
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'https://6ffa2ea252d64a8ca4c1951c15a00b5f.fleet.us-west2.gcp.elastic-cloud.com:443'
    api_key: 'MW8zMGpwb0JIOUNzblFEUWdGSDI6eEVDdHBCR3R0Q3VnRmgxdVhWQkM4QQ=='

inputs:
  - type: system/metrics
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem

agent:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
